# Generated by Django 3.1.7 on 2021-03-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210307_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='image',
            field=models.ImageField(default='/default.png', upload_to='treasure_images'),
        ),
    ]
